/**
 * @file Build-time injected version
 * @description Auto-generated by scripts/inject-version.js during the build.
 * Do not edit manually — it is overwritten every build.
 */

export const KANDOWN_VERSION = "0.23.0";
export const KANDOWN_BUILD_TIME = "2026-07-20T14:27:25.232Z";
