#!/usr/bin/env node
/**
 * @file Build-time version injector
 * @description Writes `src/lib/version.ts` with the current package version.
 * Run BEFORE the Vite build so the web app always bakes in the correct version.
 *
 * 📖 Run via: node scripts/inject-version.js
 * 📖 Also run as part of `pnpm build` (before vite build).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const PKG_ROOT = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(PKG_ROOT, 'package.json'), 'utf8'));
const version = pkg.version ?? 'unknown';

const out = `/**
 * @file Build-time injected version
 * @description Auto-generated by scripts/inject-version.js during the build.
 * Do not edit manually — it is overwritten every build.
 */

export const KANDOWN_VERSION = ${JSON.stringify(version)};
export const KANDOWN_BUILD_TIME = ${JSON.stringify(new Date().toISOString())};
`;

writeFileSync(join(PKG_ROOT, 'src', 'lib', 'version.ts'), out, 'utf8');
console.log(`✓ Injected v${version} into src/lib/version.ts`);