#!/usr/bin/env python3
"""
📖 One-shot translation injector for the new `onboarding.*` i18n keys.

Reads every locale JSON under src/lib/i18n/locales/ except en.json, merges
in the locale-specific translations defined in TRANSLATIONS, and writes
the file back with the same 2-space indentation.

The script is idempotent: running it twice produces the same output. It
preserves every other key in the file (alphabetic order may shift slightly
because we insert at the alphabetic position of the new key, not at the
end, so the diff stays small and reviewable).

Usage: python3 scripts/translate-onboarding.py
"""

import json
from pathlib import Path

LOCALES_DIR = Path(__file__).resolve().parents[1] / "src" / "lib" / "i18n" / "locales"
SOURCE_KEYS = {
    "stepLabel": "Step {{current}} of {{total}}",
    "back": "Back",
    "next": "Next",
    "getStarted": "Get Started",
    "close": "Close onboarding",
    "step1Title": "Welcome to Kandown",
    "step1Desc": "Your local-first Kanban board backed by plain Markdown files in ./tasks/. Zero database, zero lock-in, versioned with git.",
    "step2Title": "Easy task management",
    "step2Desc": "Drag and drop tasks between columns, track checklist progress, and use inline syntax like #tag, @assignee, or p1 on creation.",
    "step3Title": "Keyboard and AI driven",
    "step3Desc": "Press Cmd/Ctrl + K anytime for the Command Palette. Launch AI agents directly on tasks to automate your workflow.",
}

# 📖 Translations per locale. Every locale gets every key. Some RTL
# locales (ar, ur, fa) wrap the interpolation variables so screen readers
# and copy-paste keep them readable LTR.
TRANSLATIONS: dict[str, dict[str, str]] = {
    "ar": {
        "stepLabel": "\u200fالخطوة {{current}} من {{total}}\u200f",
        "back": "رجوع",
        "next": "التالي",
        "getStarted": "ابدأ الآن",
        "close": "إغلاق",
        "step1Title": "مرحباً بك في Kandown",
        "step1Desc": "لوحة كانبان محلية بالكامل تعمل بملفات Markdown عادية في ./tasks/. بدون قاعدة بيانات، بدون قفل، قابلة للتتبع عبر git.",
        "step2Title": "إدارة مهام سهلة",
        "step2Desc": "اسحب وأفلت المهام بين الأعمدة، وتابع تقدم القوائم، واستخدم صيغاً مثل #tag أو @assignee أو p1 عند الإنشاء.",
        "step3Title": "لوحة مفاتيح وذكاء اصطناعي",
        "step3Desc": "اضغط Cmd/Ctrl + K في أي وقت لفتح لوحة الأوامر. شغّل وكلاء الذكاء الاصطناعي مباشرة على المهام لأتمتة سير عملك.",
    },
    "bg": {
        "stepLabel": "Стъпка {{current}} от {{total}}",
        "back": "Назад",
        "next": "Напред",
        "getStarted": "Започнете",
        "close": "Затваряне",
        "step1Title": "Добре дошли в Kandown",
        "step1Desc": "Локално-first Kanban board, базиран на обикновени Markdown файлове в ./tasks/. Без база данни, без заключване, версиониран с git.",
        "step2Title": "Лесно управление на задачите",
        "step2Desc": "Плъзгайте задачите между колоните, проследявайте напредъка и използвайте синтаксис като #tag, @assignee или p1 при създаване.",
        "step3Title": "Клавиатура и AI",
        "step3Desc": "Натиснете Cmd/Ctrl + K по всяко време за командната палитра. Стартирайте AI агенти директно върху задачите.",
    },
    "bn": {
        "stepLabel": "ধাপ {{current}}/{{total}}",
        "back": "পেছনে",
        "next": "পরবর্তী",
        "getStarted": "শুরু করুন",
        "close": "বন্ধ করুন",
        "step1Title": "Kandown-এ স্বাগতম",
        "step1Desc": "সাধারণ Markdown ফাইলে তৈরি একটি লোকাল-ফার্স্ট কানবান বোর্ড, যা ./tasks/-এ থাকে। কোনো ডাটাবেস নেই, কোনো লক-ইন নেই, git দিয়ে সংস্করণযুক্ত।",
        "step2Title": "সহজ কাজ ব্যবস্থাপনা",
        "step2Desc": "কলামের মধ্যে কাজ টানুন ও ফেলুন, চেকলিস্টের অগ্রগতি দেখুন, এবং তৈরির সময় #tag, @assignee বা p1 এর মতো সিনট্যাক্স ব্যবহার করুন।",
        "step3Title": "কীবোর্ড ও AI চালিত",
        "step3Desc": "যেকোনো সময় Cmd/Ctrl + K চাপুন কমান্ড প্যালেটের জন্য। কাজের উপর সরাসরি AI এজেন্ট চালু করুন।",
    },
    "cs": {
        "stepLabel": "Krok {{current}} z {{total}}",
        "back": "Zpět",
        "next": "Další",
        "getStarted": "Začít",
        "close": "Zavřít",
        "step1Title": "Vítejte v Kandown",
        "step1Desc": "Lokální Kanban board založený na obyčejných Markdown souborech v ./tasks/. Žádná databáze, žádný vendor lock-in, verzovaný v gitu.",
        "step2Title": "Snadná správa úkolů",
        "step2Desc": "Přetahujte úkoly mezi sloupci, sledujte postup a při vytváření používejte syntaxi jako #tag, @assignee nebo p1.",
        "step3Title": "Klávesnice a AI",
        "step3Desc": "Kdykoli stiskněte Cmd/Ctrl + K pro příkazovou paletu. Spouštějte AI agenty přímo na úkolech.",
    },
    "da": {
        "stepLabel": "Trin {{current}} af {{total}}",
        "back": "Tilbage",
        "next": "Næste",
        "getStarted": "Kom i gang",
        "close": "Luk",
        "step1Title": "Velkommen til Kandown",
        "step1Desc": "Dit lokale Kanban-board med almindelige Markdown-filer i ./tasks/. Ingen database, ingen lock-in, versionsstyret med git.",
        "step2Title": "Nem opgavestyring",
        "step2Desc": "Træk og slip opgaver mellem kolonner, følg tjeklistefremdrift, og brug syntaks som #tag, @assignee eller p1 ved oprettelse.",
        "step3Title": "Tastatur og AI",
        "step3Desc": "Tryk Cmd/Ctrl + K når som helst for kommandopaletten. Start AI-agenter direkte på opgaver.",
    },
    "de": {
        "stepLabel": "Schritt {{current}} von {{total}}",
        "back": "Zurück",
        "next": "Weiter",
        "getStarted": "Loslegen",
        "close": "Schließen",
        "step1Title": "Willkommen bei Kandown",
        "step1Desc": "Dein lokal-first Kanban-Board, gespeichert als Markdown-Dateien in ./tasks/. Keine Datenbank, kein Lock-in, versioniert mit git.",
        "step2Title": "Einfache Aufgabenverwaltung",
        "step2Desc": "Ziehe Aufgaben per Drag-and-Drop zwischen Spalten, verfolge Checklisten-Fortschritt und nutze Inline-Syntax wie #tag, @assignee oder p1 beim Erstellen.",
        "step3Title": "Tastatur und KI",
        "step3Desc": "Drücke jederzeit Cmd/Ctrl + K für die Kommandopalette. Starte KI-Agenten direkt auf Aufgaben.",
    },
    "el": {
        "stepLabel": "Βήμα {{current}} από {{total}}",
        "back": "Πίσω",
        "next": "Επόμενο",
        "getStarted": "Ξεκινήστε",
        "close": "Κλείσιμο",
        "step1Title": "Καλώς ήρθατε στο Kandown",
        "step1Desc": "Ένα Kanban board τοπικής αποθήκευσης με απλά αρχεία Markdown στον φάκελο ./tasks/. Χωρίς βάση δεδομένων, χωρίς δέσμευση, με version control στο git.",
        "step2Title": "Εύκολη διαχείριση εργασιών",
        "step2Desc": "Σύρετε εργασίες μεταξύ στηλών, παρακολουθήστε την πρόοδο και χρησιμοποιήστε σύνταξη όπως #tag, @assignee ή p1 κατά τη δημιουργία.",
        "step3Title": "Πληκτρολόγιο και AI",
        "step3Desc": "Πατήστε Cmd/Ctrl + K οποτεδήποτε για την παλέτα εντολών. Εκκινήστε AI agents απευθείας σε εργασίες.",
    },
    "es": {
        "stepLabel": "Paso {{current}} de {{total}}",
        "back": "Atrás",
        "next": "Siguiente",
        "getStarted": "Empezar",
        "close": "Cerrar",
        "step1Title": "Bienvenido a Kandown",
        "step1Desc": "Tu tablero Kanban local-first respaldado por archivos Markdown en ./tasks/. Sin base de datos, sin lock-in, versionado con git.",
        "step2Title": "Gestión de tareas sencilla",
        "step2Desc": "Arrastra y suelta tareas entre columnas, sigue el progreso de checklists y usa sintaxis como #tag, @assignee o p1 al crear.",
        "step3Title": "Teclado e IA",
        "step3Desc": "Pulsa Cmd/Ctrl + K en cualquier momento para abrir la paleta de comandos. Lanza agentes de IA directamente sobre las tareas.",
    },
    "et": {
        "stepLabel": "Samm {{current}}/{{total}}",
        "back": "Tagasi",
        "next": "Edasi",
        "getStarted": "Alusta",
        "close": "Sulge",
        "step1Title": "Tere tulemast Kandowni",
        "step1Desc": "Sinu kohalik Kanban-tahvel, mis põhineb tavalistel Markdown-failidel kaustas ./tasks/. Ilma andmebaasi ja lukustuseta, versioonitud git-iga.",
        "step2Title": "Lihtne ülesannete haldus",
        "step2Desc": "Lohista ülesandeid veergude vahel, jälgi kontrollnimekirjade edenemist ja kasuta loomisel süntaksit nagu #tag, @assignee või p1.",
        "step3Title": "Klaviatuur ja AI",
        "step3Desc": "Vajuta igal ajal Cmd/Ctrl + K käsuvälja jaoks. Käivita AI-agendid otse ülesannetel.",
    },
    "fa": {
        "stepLabel": "\u200fمرحله {{current}} از {{total}}\u200f",
        "back": "بازگشت",
        "next": "بعدی",
        "getStarted": "شروع",
        "close": "بستن",
        "step1Title": "به Kandown خوش آمدید",
        "step1Desc": "تخته Kanban محلی شما با فایل‌های ساده Markdown در ./tasks/. بدون پایگاه داده، بدون وابستگی، نسخه‌بندی با git.",
        "step2Title": "مدیریت آسان وظایف",
        "step2Desc": "وظایف را بین ستون‌ها بکشید و رها کنید، پیشرفت چک‌لیست‌ها را دنبال کنید و از نحو #tag، @assignee یا p1 در ساخت استفاده کنید.",
        "step3Title": "صفحه‌کلید و هوش مصنوعی",
        "step3Desc": "هر زمان Cmd/Ctrl + K را برای فرمان‌پالت بزنید. عامل‌های هوش مصنوعی را مستقیماً روی وظایف اجرا کنید.",
    },
    "fi": {
        "stepLabel": "Vaihe {{current}}/{{total}}",
        "back": "Takaisin",
        "next": "Seuraava",
        "getStarted": "Aloita",
        "close": "Sulje",
        "step1Title": "Tervetuloa Kandowniin",
        "step1Desc": "Paikallinen Kanban-taulusi, joka perustuu tavallisiin Markdown-tiedostoihin hakemistossa ./tasks/. Ei tietokantaa, ei lukkiutumista, versioitu gitillä.",
        "step2Title": "Helppo tehtävien hallinta",
        "step2Desc": "Vedä ja pudota tehtäviä sarakkeiden välillä, seuraa tarkistuslistojen edistymistä ja käytä syntaksia kuten #tag, @assignee tai p1 luodessasi.",
        "step3Title": "Näppäimistö ja tekoäly",
        "step3Desc": "Paina Cmd/Ctrl + K milloin tahansa komentosäiliötä varten. Käynnistä tekoälyagentit suoraan tehtäville.",
    },
    "fr": {
        "stepLabel": "Étape {{current}} sur {{total}}",
        "back": "Retour",
        "next": "Suivant",
        "getStarted": "Commencer",
        "close": "Fermer",
        "step1Title": "Bienvenue dans Kandown",
        "step1Desc": "Votre tableau Kanban local-first basé sur de simples fichiers Markdown dans ./tasks/. Zéro base de données, zéro verrouillage, versionné avec git.",
        "step2Title": "Gestion des tâches simplifiée",
        "step2Desc": "Glissez-déposez les tâches entre les colonnes, suivez la progression des checklists et utilisez la syntaxe #tag, @assignee ou p1 à la création.",
        "step3Title": "Clavier et IA",
        "step3Desc": "Appuyez sur Cmd/Ctrl + K à tout moment pour la palette de commandes. Lancez des agents IA directement sur les tâches.",
    },
    "gu": {
        "stepLabel": "પગથિયું {{current}}/{{total}}",
        "back": "પાછળ",
        "next": "આગળ",
        "getStarted": "શરૂ કરો",
        "close": "બંધ કરો",
        "step1Title": "Kandown માં આપનું સ્વાગત છે",
        "step1Desc": "./tasks/ માં સાદા Markdown ફાઇલો સાથેનું તમારું લોકલ-ફર્સ્ટ કેન્બન બોર્ડ. કોઈ ડેટાબેઝ નહીં, કોઈ લોક-ઇન નહીં, git સાથે વર્ઝન કરેલ.",
        "step2Title": "સરળ કાર્ય વ્યવસ્થાપન",
        "step2Desc": "કાર્યોને કૉલમ્સ વચ્ચે ખેંચો અને મૂકો, ચેકલિસ્ટ પ્રગતિ ટ્રેક કરો અને બનાવતી વખતે #tag, @assignee અથવા p1 જેવી સિન્ટેક્સ વાપરો.",
        "step3Title": "કીબોર્ડ અને AI",
        "step3Desc": "કોઈ પણ સમયે કમાન્ડ પેલેટ માટે Cmd/Ctrl + K દબાવો. AI એજન્ટ્સને સીધા કાર્યો પર શરૂ કરો.",
    },
    "hi": {
        "stepLabel": "चरण {{current}}/{{total}}",
        "back": "पीछे",
        "next": "अगला",
        "getStarted": "शुरू करें",
        "close": "बंद करें",
        "step1Title": "Kandown में आपका स्वागत है",
        "step1Desc": "सादे Markdown फाइलों पर आधारित आपका लोकल-फर्स्ट कानबन बोर्ड ./tasks/ में। कोई डेटाबेस नहीं, कोई लॉक-इन नहीं, git के साथ वर्ज़न किया गया।",
        "step2Title": "आसान कार्य प्रबंधन",
        "step2Desc": "कार्यों को कॉलम के बीच खींचें और छोड़ें, चेकलिस्ट प्रगति ट्रैक करें, और बनाते समय #tag, @assignee, या p1 जैसे सिंटैक्स का उपयोग करें।",
        "step3Title": "कीबोर्ड और AI",
        "step3Desc": "कमांड पैलेट के लिए कभी भी Cmd/Ctrl + K दबाएं। कार्यों पर सीधे AI एजेंट लॉन्च करें।",
    },
    "hr": {
        "stepLabel": "Korak {{current}} od {{total}}",
        "back": "Natrag",
        "next": "Dalje",
        "getStarted": "Kreni",
        "close": "Zatvori",
        "step1Title": "Dobrodošli u Kandown",
        "step1Desc": "Vaš lokalni Kanban board temeljen na običnim Markdown datotekama u ./tasks/. Bez baze podataka, bez zaključavanja, verzioniran u git-u.",
        "step2Title": "Jednostavno upravljanje zadacima",
        "step2Desc": "Povlačite zadatke između stupaca, pratite napredak popisa i koristite sintaksu poput #tag, @assignee ili p1 pri stvaranju.",
        "step3Title": "Tipkovnica i AI",
        "step3Desc": "Pritisnite Cmd/Ctrl + K u bilo kojem trenutku za paletu naredbi. Pokrenite AI agente izravno na zadacima.",
    },
    "hu": {
        "stepLabel": "{{current}} / {{total}} lépés",
        "back": "Vissza",
        "next": "Tovább",
        "getStarted": "Kezdjük",
        "close": "Bezárás",
        "step1Title": "Üdvözöl a Kandown",
        "step1Desc": "Helyi Kanban-táblád egyszerű Markdown fájlokkal a ./tasks/ mappában. Nincs adatbázis, nincs lezárás, git-tel verziózva.",
        "step2Title": "Egyszerű feladatkezelés",
        "step2Desc": "Húzd és dobd a feladatokat az oszlopok között, kövesd a checklisták haladását, és használj #tag, @assignee vagy p1 szintaxist létrehozáskor.",
        "step3Title": "Billentyűzet és AI",
        "step3Desc": "Bármikor nyomd meg a Cmd/Ctrl + K billentyűkombinációt a parancspalettához. Indíts AI ügynököket közvetlenül a feladatokon.",
    },
    "id": {
        "stepLabel": "Langkah {{current}} dari {{total}}",
        "back": "Kembali",
        "next": "Berikutnya",
        "getStarted": "Mulai",
        "close": "Tutup",
        "step1Title": "Selamat datang di Kandown",
        "step1Desc": "Papan Kanban lokal-pertama Anda yang ditopang oleh file Markdown biasa di ./tasks/. Tanpa basis data, tanpa lock-in, diverisikan dengan git.",
        "step2Title": "Manajemen tugas mudah",
        "step2Desc": "Tarik dan lepas tugas antar kolom, lacak progres checklist, dan gunakan sintaksis seperti #tag, @assignee, atau p1 saat membuat.",
        "step3Title": "Papan kunci dan AI",
        "step3Desc": "Tekan Cmd/Ctrl + K kapan saja untuk palet perintah. Luncurkan agen AI langsung pada tugas.",
    },
    "it": {
        "stepLabel": "Passo {{current}} di {{total}}",
        "back": "Indietro",
        "next": "Avanti",
        "getStarted": "Inizia",
        "close": "Chiudi",
        "step1Title": "Benvenuto in Kandown",
        "step1Desc": "La tua bacheca Kanban local-first basata su semplici file Markdown in ./tasks/. Zero database, zero vincoli, versionata con git.",
        "step2Title": "Gestione delle attività semplice",
        "step2Desc": "Trascina e rilascia le attività tra le colonne, monitora l'avanzamento delle checklist e usa sintassi come #tag, @assignee o p1 alla creazione.",
        "step3Title": "Tastiera e IA",
        "step3Desc": "Premi Cmd/Ctrl + K in qualsiasi momento per la palette dei comandi. Avvia agenti IA direttamente sulle attività.",
    },
    "ja": {
        "stepLabel": "ステップ {{current}} / {{total}}",
        "back": "戻る",
        "next": "次へ",
        "getStarted": "はじめる",
        "close": "閉じる",
        "step1Title": "Kandownへようこそ",
        "step1Desc": "./tasks/ のMarkdownファイルだけで動くローカルファーストのカンバンボード。データベースもロックインも不要、gitでバージョン管理されます。",
        "step2Title": "かんたんなタスク管理",
        "step2Desc": "タスクをカラム間でドラッグ&ドロップし、チェックリストの進捗を追跡。作成時には #tag・@assignee・p1 のようなインライン構文が使えます。",
        "step3Title": "キーボードとAI",
        "step3Desc": "コマンドパレットは Cmd/Ctrl + K でいつでも開けます。タスクに対してAIエージェントを直接起動できます。",
    },
    "km": {
        "stepLabel": "ជំហាន {{current}} នៃ {{total}}",
        "back": "ថយក្រោយ",
        "next": "បន្ទាប់",
        "getStarted": "ចាប់ផ្តើម",
        "close": "បិទ",
        "step1Title": "ស្វាគមន៍មកកាន់ Kandown",
        "step1Desc": "ក្តារ Kanban ផ្តាច់មូលរបស់អ្នក ដែលបង្កើតពីឯកសារ Markdown ធម្មតានៅក្នុង ./tasks/. គ្មានមូលដ្ឋានទិន្នន័យ គ្មានការចាក់សោ ជាមួយ git ។",
        "step2Title": "ការគ្រប់គ្រងភារកិច្ចងាយស្រួល",
        "step2Desc": "អូសនិងទម្លាក់ភារកិច្ចរវាងជួរឈរ តាមដានវឌ្ឍនភាពបញ្ជីត្រួតពិនិត្យ និងប្រើវាក្យសម្ព័ន្ធដូចជា #tag, @assignee ឬ p1 ពេលបង្កើត។",
        "step3Title": "ក្តារចុចនិង AI",
        "step3Desc": "ចុច Cmd/Ctrl + K គ្រប់ពេលសម្រាប់របារពាក្យបញ្ជា។ បើកភ្នាក់ងារ AI ដោយផ្ទាល់លើភារកិច្ច។",
    },
    "kn": {
        "stepLabel": "ಹಂತ {{current}}/{{total}}",
        "back": "ಹಿಂದೆ",
        "next": "ಮುಂದೆ",
        "getStarted": "ಪ್ರಾರಂಭಿಸಿ",
        "close": "ಮುಚ್ಚಿ",
        "step1Title": "Kandown ಗೆ ಸ್ವಾಗತ",
        "step1Desc": "./tasks/ ನಲ್ಲಿ ಸಾಮಾನ್ಯ Markdown ಫೈಲ್‌ಗಳಿಂದ ನಿಮ್ಮ ಸ್ಥಳೀಯ-ಮೊದಲ Kanban ಬೋರ್ಡ್. ಯಾವುದೇ ಡೇಟಾಬೇಸ್ ಇಲ್ಲ, ಯಾವುದೇ ಲಾಕ್-ಇನ್ ಇಲ್ಲ, git ನೊಂದಿಗೆ ಆವೃತ್ತಿಯಾಗಿದೆ.",
        "step2Title": "ಸುಲಭ ಕಾರ್ಯ ನಿರ್ವಹಣೆ",
        "step2Desc": "ಕಾರ್ಯಗಳನ್ನು ಕಾಲಮ್‌ಗಳ ನಡುವೆ ಎಳೆಯಿರಿ ಮತ್ತು ಬಿಡಿ, ಚೆಕ್‌ಲಿಸ್ಟ್ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಮತ್ತು ರಚಿಸುವಾಗ #tag, @assignee ಅಥವಾ p1 ನಂತಹ ಸಿಂಟ್ಯಾಕ್ಸ್ ಬಳಸಿ.",
        "step3Title": "ಕೀಲೋಮಕ ಮತ್ತು AI",
        "step3Desc": "ಆಜ್ಞಾ ಪ್ಯಾಲೆಟ್‌ಗಾಗಿ ಯಾವುದೇ ಸಮಯದಲ್ಲಿ Cmd/Ctrl + K ಒತ್ತಿ. AI ಏಜೆಂಟ್‌ಗಳನ್ನು ನೇರವಾಗಿ ಕಾರ್ಯಗಳ ಮೇಲೆ ಪ್ರಾರಂಭಿಸಿ.",
    },
    "ko": {
        "stepLabel": "{{total}}단계 중 {{current}}단계",
        "back": "뒤로",
        "next": "다음",
        "getStarted": "시작하기",
        "close": "닫기",
        "step1Title": "Kandown에 오신 것을 환영합니다",
        "step1Desc": "./tasks/의 평범한 Markdown 파일로 동작하는 로컬 우선 칸반 보드입니다. 데이터베이스도, 락인도 없고 git으로 버전 관리됩니다.",
        "step2Title": "손쉬운 작업 관리",
        "step2Desc": "작업을 열 간에 드래그 앤 드롭하고, 체크리스트 진행 상황을 추적하며, 생성 시 #tag, @assignee, p1 같은 인라인 구문을 사용하세요.",
        "step3Title": "키보드와 AI",
        "step3Desc": "언제든지 Cmd/Ctrl + K로 명령 팔레트를 여세요. 작업에 AI 에이전트를 직접 실행할 수 있습니다.",
    },
    "lt": {
        "stepLabel": "Žingsnis {{current}} iš {{total}}",
        "back": "Atgal",
        "next": "Toliau",
        "getStarted": "Pradėti",
        "close": "Uždaryti",
        "step1Title": "Sveiki atvykę į Kandown",
        "step1Desc": "Jūsų vietinis Kanban valdytojas, paremtas paprastais Markdown failais ./tasks/. Be duomenų bazės, be priklausomybės, versijuojamas su git.",
        "step2Title": "Lengvas užduočių valdymas",
        "step2Desc": "Tempkite užduotis tarp stulpelių, sekite sąrašų pažangą ir kurdami naudokite #tag, @assignee ar p1 sintaksę.",
        "step3Title": "Klaviatūra ir DI",
        "step3Desc": "Bet kada paspauskite Cmd/Ctrl + K komandų paletei. Paleiskite DI agentus tiesiogiai ant užduočių.",
    },
    "lv": {
        "stepLabel": "Solis {{current}} no {{total}}",
        "back": "Atpakaļ",
        "next": "Tālāk",
        "getStarted": "Sākt",
        "close": "Aizvērt",
        "step1Title": "Laipni lūgti Kandown",
        "step1Desc": "Jūsu lokālais Kanban dēlis, kas balstīts uz vienkāršiem Markdown failiem mapē ./tasks/. Bez datubāzes, bez piesaistes, versijots ar git.",
        "step2Title": "Viegla uzdevumu pārvaldība",
        "step2Desc": "Velciet uzdevumus starp kolonnām, izsekojiet kontrolsarakstu progresu un veidošanas laikā izmantojiet #tag, @assignee vai p1 sintaksi.",
        "step3Title": "Tastatūra un AI",
        "step3Desc": "Jebkurā brīdī nospiediet Cmd/Ctrl + K komandu paletei. Palaidiet AI aģentus tieši uzdevumos.",
    },
    "ml": {
        "stepLabel": "ഘട്ടം {{current}}/{{total}}",
        "back": "പുറകോട്ട്",
        "next": "അടുത്തത്",
        "getStarted": "തുടങ്ങാം",
        "close": "അടയ്ക്കുക",
        "step1Title": "Kandown-ലേക്ക് സ്വാഗതം",
        "step1Desc": "./tasks/-ലെ സാധാരണ Markdown ഫയലുകൾ ഉപയോഗിച്ചുള്ള നിങ്ങളുടെ ലോക്കൽ-ഫസ്റ്റ് കൻബൻ ബോർഡ്. ഡാറ്റാബേസ് ഇല്ല, ലോക്ക്-ഇൻ ഇല്ല, git ഉപയോഗിച്ച് വേർഷൻ ചെയ്തിരിക്കുന്നു.",
        "step2Title": "എളുപ്പമുള്ള ടാസ്‌ക് മാനേജ്‌മെന്റ്",
        "step2Desc": "ടാസ്‌ക്കുകൾ കോളങ്ങൾ തമ്മിൽ വലിച്ചിടുക, ചെക്ക്‌ലിസ്റ്റ് പുരോഗതി ട്രാക്ക് ചെയ്യുക, സൃഷ്ടിക്കുമ്പോൾ #tag, @assignee അല്ലെങ്കിൽ p1 പോലുള്ള വാക്യഘടന ഉപയോഗിക്കുക.",
        "step3Title": "കീബോർഡും AI-യും",
        "step3Desc": "കമാൻഡ് പാലറ്റിനായി എപ്പോൾ വേണമെങ്കിലും Cmd/Ctrl + K അമർത്തുക. ടാസ്‌ക്കുകളിൽ നേരിട്ട് AI ഏജന്റുകൾ പ്രവർത്തിപ്പിക്കുക.",
    },
    "mr": {
        "stepLabel": "टप्पा {{current}}/{{total}}",
        "back": "मागे",
        "next": "पुढे",
        "getStarted": "सुरू करा",
        "close": "बंद करा",
        "step1Title": "Kandown मध्ये आपले स्वागत आहे",
        "step1Desc": "सामान्य Markdown फाइल्सवर आधारित तुमचा लोकल-फर्स्ट कानबन बोर्ड, ./tasks/ मध्ये. डेटाबेस नाही, लॉक-इन नाही, git सह आवृत्ती.",
        "step2Title": "सोपे कार्य व्यवस्थापन",
        "step2Desc": "कार्ये स्तंभांमध्ये ड्रॅग आणि ड्रॉप करा, चेकलिस्ट प्रगती ट्रॅक करा, आणि तयार करताना #tag, @assignee किंवा p1 सारखी सिंटॅक्स वापरा.",
        "step3Title": "कीबोर्ड आणि AI",
        "step3Desc": "कमांड पॅलेटसाठी कधीही Cmd/Ctrl + K दाबा. कार्यांवर थेट AI एजंट्स लाँच करा.",
    },
    "ms": {
        "stepLabel": "Langkah {{current}} daripada {{total}}",
        "back": "Kembali",
        "next": "Seterusnya",
        "getStarted": "Mula",
        "close": "Tutup",
        "step1Title": "Selamat datang ke Kandown",
        "step1Desc": "Papan Kanban setempat anda yang disokong oleh fail Markdown biasa di ./tasks/. Tiada pangkalan data, tiada lock-in, diverisikan dengan git.",
        "step2Title": "Pengurusan tugas yang mudah",
        "step2Desc": "Seret dan lepas tugas antara lajur, jejak progres senarai semak, dan gunakan sintaks seperti #tag, @assignee atau p1 semasa membuat.",
        "step3Title": "Papan kekunci dan AI",
        "step3Desc": "Tekan Cmd/Ctrl + K pada bila-bila masa untuk palet perintah. Lancarkan ejen AI secara terus pada tugas.",
    },
    "my": {
        "stepLabel": "အဆင့် {{current}}/{{total}}",
        "back": "နောက်သို့",
        "next": "ရှေ့သို့",
        "getStarted": "စတင်ရန်",
        "close": "ပိတ်ရန်",
        "step1Title": "Kandown မှ ကြိုဆိုပါသည်",
        "step1Desc": "./tasks/ ရှိ ရိုးရိုး Markdown ဖိုင်များဖြင့် သင်၏ ဒေသတွင်း-ဦးစားပေး Kanban ဘုတ်။ ဒေတာဘေ့စ် မရှိ၊ lock-in မရှိ၊ git ဖြင့် version ပြုလုပ်ထားသည်။",
        "step2Title": "လွယ်ကူသော လုပ်ငန်းစဉ် စီမံခန့်ခွဲမှု",
        "step2Desc": "ကော်လံများကြား လုပ်ငန်းများကို ဆွဲယူ၍ ချပါ၊ checklist တိုးတက်မှုကို ခြေရာခံပါ၊ ဖန်တီးချိန်တွင် #tag၊ @assignee သို့မဟုတ် p1 ကဲ့သို့ syntax များကို သုံးပါ။",
        "step3Title": "ကီးဘုတ်နှင့် AI",
        "step3Desc": "Command palette အတွက် အချိန်မရွေး Cmd/Ctrl + K ကို နှိပ်ပါ။ AI အေးဂျင့်များကို လုပ်ငန်းများပေါ်တွင် တိုက်ရိုက် လည်ပတ်ပါ။",
    },
    "nl": {
        "stepLabel": "Stap {{current}} van {{total}}",
        "back": "Terug",
        "next": "Volgende",
        "getStarted": "Aan de slag",
        "close": "Sluiten",
        "step1Title": "Welkom bij Kandown",
        "step1Desc": "Je local-first Kanban-bord met gewone Markdown-bestanden in ./tasks/. Geen database, geen lock-in, versioneer met git.",
        "step2Title": "Eenvoudig taakbeheer",
        "step2Desc": "Sleep taken tussen kolommen, volg de voortgang van checklists en gebruik inline-syntaxis zoals #tag, @assignee of p1 bij het aanmaken.",
        "step3Title": "Toetsenbord en AI",
        "step3Desc": "Druk op elk moment op Cmd/Ctrl + K voor het opdrachtenpalet. Start AI-agenten direct op taken.",
    },
    "no": {
        "stepLabel": "Trinn {{current}} av {{total}}",
        "back": "Tilbake",
        "next": "Neste",
        "getStarted": "Kom i gang",
        "close": "Lukk",
        "step1Title": "Velkommen til Kandown",
        "step1Desc": "Ditt lokale Kanban-brett med vanlige Markdown-filer i ./tasks/. Ingen database, ingen lock-in, versjonskontrollert med git.",
        "step2Title": "Enkel oppgavehåndtering",
        "step2Desc": "Dra og slipp oppgaver mellom kolonner, følg fremdriften på sjekklister, og bruk syntaks som #tag, @assignee eller p1 ved opprettelse.",
        "step3Title": "Tastatur og AI",
        "step3Desc": "Trykk Cmd/Ctrl + K når som helst for kommandopaletten. Start AI-agenter direkte på oppgaver.",
    },
    "pl": {
        "stepLabel": "Krok {{current}} z {{total}}",
        "back": "Wstecz",
        "next": "Dalej",
        "getStarted": "Zacznij",
        "close": "Zamknij",
        "step1Title": "Witamy w Kandown",
        "step1Desc": "Twoja lokalna tablica Kanban oparta na zwykłych plikach Markdown w ./tasks/. Bez bazy danych, bez uzależnienia, wersjonowana w git.",
        "step2Title": "Łatwe zarządzanie zadaniami",
        "step2Desc": "Przeciągaj zadania między kolumnami, śledź postęp checklist i używaj składni takiej jak #tag, @assignee lub p1 przy tworzeniu.",
        "step3Title": "Klawiatura i AI",
        "step3Desc": "Naciśnij Cmd/Ctrl + K w dowolnym momencie, aby otworzyć paletę poleceń. Uruchamiaj agentów AI bezpośrednio na zadaniach.",
    },
    "pt": {
        "stepLabel": "Passo {{current}} de {{total}}",
        "back": "Voltar",
        "next": "Próximo",
        "getStarted": "Começar",
        "close": "Fechar",
        "step1Title": "Bem-vindo ao Kandown",
        "step1Desc": "O seu quadro Kanban local-first suportado por ficheiros Markdown simples em ./tasks/. Sem base de dados, sem lock-in, versionado com git.",
        "step2Title": "Gestão de tarefas fácil",
        "step2Desc": "Arraste e largue tarefas entre colunas, acompanhe o progresso de checklists e use sintaxe como #tag, @assignee ou p1 ao criar.",
        "step3Title": "Teclado e IA",
        "step3Desc": "Prima Cmd/Ctrl + K a qualquer momento para a paleta de comandos. Lance agentes de IA diretamente em tarefas.",
    },
    "ro": {
        "stepLabel": "Pasul {{current}} din {{total}}",
        "back": "Înapoi",
        "next": "Înainte",
        "getStarted": "Începe",
        "close": "Închide",
        "step1Title": "Bun venit la Kandown",
        "step1Desc": "Tabloul tău Kanban local-first, susținut de fișiere Markdown simple în ./tasks/. Fără bază de date, fără blocaj, versionat cu git.",
        "step2Title": "Gestionare ușoară a sarcinilor",
        "step2Desc": "Trage și plasează sarcini între coloane, urmărește progresul checklist-urilor și folosește sintaxa #tag, @assignee sau p1 la creare.",
        "step3Title": "Tastatură și AI",
        "step3Desc": "Apasă Cmd/Ctrl + K oricând pentru paleta de comenzi. Lansează agenți AI direct pe sarcini.",
    },
    "ru": {
        "stepLabel": "Шаг {{current}} из {{total}}",
        "back": "Назад",
        "next": "Далее",
        "getStarted": "Начать",
        "close": "Закрыть",
        "step1Title": "Добро пожаловать в Kandown",
        "step1Desc": "Ваш локальный Kanban на обычных Markdown-файлах в ./tasks/. Никаких баз данных и привязок, версионируется через git.",
        "step2Title": "Простое управление задачами",
        "step2Desc": "Перетаскивайте задачи между колонками, отслеживайте прогресс чек-листов и используйте синтаксис #tag, @assignee или p1 при создании.",
        "step3Title": "Клавиатура и ИИ",
        "step3Desc": "Нажмите Cmd/Ctrl + K в любой момент, чтобы открыть командную палитру. Запускайте ИИ-агентов прямо на задачах.",
    },
    "si": {
        "stepLabel": "පියවර {{current}}/{{total}}",
        "back": "ආපසු",
        "next": "ඊළඟ",
        "getStarted": "ආරම්භ කරන්න",
        "close": "වසන්න",
        "step1Title": "Kandown වෙත සාදරයෙන් පිළිගනිමු",
        "step1Desc": "ඔබේ දේශීය-පළමු Kanban පුවරුව ./tasks/ හි සාමාන්‍ය Markdown ගොනු මත පදනම් වේ. දත්ත සමුදා නැත, lock-in නැත, git සමඟ අනුවාදය.",
        "step2Title": "පහසු කාර්ය කළමනාකරණය",
        "step2Desc": "කාර්යයන් තීරු අතර ඇදගෙන දමන්න, පරීක්ෂා ලැයිස්තු ප්‍රගතිය නිරීක්ෂණය කරන්න, සහ නිර්මාණය කරන විට #tag, @assignee හෝ p1 වැනි වාක්‍ය රචනාව භාවිතා කරන්න.",
        "step3Title": "යතුකුඩු සහ AI",
        "step3Desc": "විධාන පැලට් සඳහා ඕනෑම වේලාවක Cmd/Ctrl + K ඔබන්න. AI නියෝජිතයින් කාර්යයන් මත සෘජුවම දියත් කරන්න.",
    },
    "sk": {
        "stepLabel": "Krok {{current}} z {{total}}",
        "back": "Späť",
        "next": "Ďalej",
        "getStarted": "Začať",
        "close": "Zavrieť",
        "step1Title": "Vitajte v Kandown",
        "step1Desc": "Vaša lokálna Kanban nástenka založená na obyčajných Markdown súboroch v ./tasks/. Žiadna databáza, žiadny vendor lock-in, verziovaná v gite.",
        "step2Title": "Jednoduchá správa úloh",
        "step2Desc": "Ťahajte úlohy medzi stĺpcami, sledujte postup kontrolných zoznamov a pri vytváraní používajte syntax ako #tag, @assignee alebo p1.",
        "step3Title": "Klávesnica a AI",
        "step3Desc": "Kedykoľvek stlačte Cmd/Ctrl + K pre príkazovú paletu. Spúšťajte AI agentov priamo na úlohách.",
    },
    "sl": {
        "stepLabel": "Korak {{current}} od {{total}}",
        "back": "Nazaj",
        "next": "Naprej",
        "getStarted": "Začni",
        "close": "Zapri",
        "step1Title": "Dobrodošli v Kandown",
        "step1Desc": "Vaša lokalna Kanban tabla na osnovi preprostih Markdown datotek v ./tasks/. Brez podatkovne baze, brez zaklepanja, različice v gitu.",
        "step2Title": "Enostavno upravljanje nalog",
        "step2Desc": "Vlecite naloge med stolpci, sledite napredku seznamov in pri ustvarjanju uporabite sintakso, kot so #tag, @assignee ali p1.",
        "step3Title": "Tipkovnica in AI",
        "step3Desc": "Kdaj koli pritisnite Cmd/Ctrl + K za ukazno paleto. Zaženite AI agente neposredno na nalogah.",
    },
    "sr": {
        "stepLabel": "Korak {{current}} od {{total}}",
        "back": "Nazad",
        "next": "Dalje",
        "getStarted": "Kreni",
        "close": "Zatvori",
        "step1Title": "Dobrodošli u Kandown",
        "step1Desc": "Vaša lokalna Kanban tabla zasnovana na običnim Markdown fajlovima u ./tasks/. Bez baze podataka, bez zaključavanja, verzionisana u git-u.",
        "step2Title": "Jednostavno upravljanje zadacima",
        "step2Desc": "Vucite zadatke između kolona, pratite napredak lista i koristite sintaksu poput #tag, @assignee ili p1 pri kreiranju.",
        "step3Title": "Tastatura i AI",
        "step3Desc": "Pritisnite Cmd/Ctrl + K u bilo kom trenutku za komandnu paletu. Pokrenite AI agente direktno na zadacima.",
    },
    "sv": {
        "stepLabel": "Steg {{current}} av {{total}}",
        "back": "Tillbaka",
        "next": "Nästa",
        "getStarted": "Kom igång",
        "close": "Stäng",
        "step1Title": "Välkommen till Kandown",
        "step1Desc": "Din lokal-first Kanban-tavla med vanliga Markdown-filer i ./tasks/. Ingen databas, ingen inlåsning, versionshanterad med git.",
        "step2Title": "Enkel uppgiftshantering",
        "step2Desc": "Dra och släpp uppgifter mellan kolumner, följ checklistans framsteg och använd syntax som #tag, @assignee eller p1 när du skapar.",
        "step3Title": "Tangentbord och AI",
        "step3Desc": "Tryck när som helst på Cmd/Ctrl + K för kommandopaletten. Starta AI-agenter direkt på uppgifter.",
    },
    "ta": {
        "stepLabel": "படி {{current}}/{{total}}",
        "back": "பின்",
        "next": "அடுத்து",
        "getStarted": "தொடங்கு",
        "close": "மூடு",
        "step1Title": "Kandown-க்கு வரவேற்கிறோம்",
        "step1Desc": "./tasks/ இல் உள்ள எளிய Markdown கோப்புகளால் ஆன உங்கள் லோக்கல்-ஃபர்ஸ்ட் கான்பன் பலகை. தரவுத்தளம் இல்லை, பூட்டல் இல்லை, git மூலம் பதிப்பு.",
        "step2Title": "எளிய பணி மேலாண்மை",
        "step2Desc": "பணிகளை நெடுவரிசைகளுக்கு இடையில் இழுத்து விடுங்கள், சோதனைப்பட்டியல் முன்னேற்றத்தை கண்காணியுங்கள், உருவாக்கும்போது #tag, @assignee அல்லது p1 தொடரியல் பயன்படுத்துங்கள்.",
        "step3Title": "விசைப்பலகை மற்றும் AI",
        "step3Desc": "கட்டளைத் தட்டுக்கு எப்போது வேண்டுமானாலும் Cmd/Ctrl + K அழுத்துங்கள். பணிகளில் நேரடியாக AI முகவர்களைத் தொடங்குங்கள்.",
    },
    "te": {
        "stepLabel": "దశ {{current}}/{{total}}",
        "back": "వెనుకకు",
        "next": "తదుపరి",
        "getStarted": "ప్రారంభించండి",
        "close": "మూసివేయండి",
        "step1Title": "Kandownకి స్వాగతం",
        "step1Desc": "./tasks/లోని సాధారణ Markdown ఫైళ్ళపై ఆధారపడిన మీ లోకల్-ఫస్ట్ కాన్బన్ బోర్డ్. డేటాబేస్ లేదు, లాక్-ఇన్ లేదు, gitతో వెర్షన్ చేయబడింది.",
        "step2Title": "సులభమైన పని నిర్వహణ",
        "step2Desc": "పనులను కాలమ్‌ల మధ్య డ్రాగ్ చేసి వదలండి, చెక్‌లిస్ట్ ప్రగతిని ట్రాక్ చేయండి మరియు సృష్టించేటప్పుడు #tag, @assignee లేదా p1 వంటి సింటాక్స్ ఉపయోగించండి.",
        "step3Title": "కీబోర్డ్ మరియు AI",
        "step3Desc": "కమాండ్ ప్యాలెట్ కోసం ఎప్పుడైనా Cmd/Ctrl + K నొక్కండి. పనులపై నేరుగా AI ఏజెంట్‌లను ప్రారంభించండి.",
    },
    "th": {
        "stepLabel": "ขั้นตอน {{current}} จาก {{total}}",
        "back": "กลับ",
        "next": "ถัดไป",
        "getStarted": "เริ่มต้น",
        "close": "ปิด",
        "step1Title": "ยินดีต้อนรับสู่ Kandown",
        "step1Desc": "บอร์ด Kanban แบบ local-first ที่ใช้ไฟล์ Markdown ธรรมดาใน ./tasks/. ไม่มีฐานข้อมูล ไม่มี lock-in ใช้ git จัดการเวอร์ชัน",
        "step2Title": "จัดการงานได้ง่าย",
        "step2Desc": "ลากและวางงานระหว่างคอลัมน์ ติดตามความคืบหน้าของเช็คลิสต์ และใช้ไวยากรณ์ เช่น #tag, @assignee หรือ p1 ตอนสร้าง",
        "step3Title": "คีย์บอร์ดและ AI",
        "step3Desc": "กด Cmd/Ctrl + K เมื่อใดก็ได้เพื่อเปิด command palette เปิดเอเจนต์ AI บนงานโดยตรง",
    },
    "tr": {
        "stepLabel": "Adım {{current}} / {{total}}",
        "back": "Geri",
        "next": "İleri",
        "getStarted": "Başla",
        "close": "Kapat",
        "step1Title": "Kandown'a hoş geldiniz",
        "step1Desc": "./tasks/ içindeki sade Markdown dosyalarıyla çalışan yerel öncelikli Kanban panonuz. Veritabanı yok, kilitlenme yok, git ile sürümlenmiş.",
        "step2Title": "Kolay görev yönetimi",
        "step2Desc": "Görevleri sütunlar arasında sürükleyip bırakın, checklist ilerlemesini takip edin ve oluştururken #tag, @assignee veya p1 gibi satır içi sözdizimi kullanın.",
        "step3Title": "Klavye ve yapay zeka",
        "step3Desc": "Komut paleti için istediğiniz zaman Cmd/Ctrl + K tuşlarına basın. Yapay zeka ajanlarını doğrudan görevler üzerinde başlatın.",
    },
    "uk": {
        "stepLabel": "Крок {{current}} з {{total}}",
        "back": "Назад",
        "next": "Далі",
        "getStarted": "Почати",
        "close": "Закрити",
        "step1Title": "Ласкаво просимо до Kandown",
        "step1Desc": "Ваш локальний Kanban на звичайних Markdown-файлах у ./tasks/. Без баз даних і прив'язок, версіонується через git.",
        "step2Title": "Просте керування задачами",
        "step2Desc": "Перетягуйте задачі між колонками, відстежуйте прогрес чек-лістів і використовуйте синтаксис #tag, @assignee або p1 під час створення.",
        "step3Title": "Клавіатура та ШІ",
        "step3Desc": "Натисніть Cmd/Ctrl + K у будь-який момент, щоб відкрити командну палітру. Запускайте ШІ-агентів прямо на задачах.",
    },
    "ur": {
        "stepLabel": "\u200fمرحلہ {{current}} از {{total}}\u200f",
        "back": "واپس",
        "next": "اگلا",
        "getStarted": "شروع کریں",
        "close": "بند کریں",
        "step1Title": "Kandown میں خوش آمدید",
        "step1Desc": "آپ کا لوکل-فرسٹ کانبن بورڈ جو ./tasks/ میں سادہ Markdown فائلوں پر مبنی ہے۔ نہ ڈیٹا بیس، نہ لاک اِن، git کے ساتھ ورژن۔",
        "step2Title": "آسان کام کا انتظام",
        "step2Desc": "کاموں کو کالمز کے درمیان گھسیٹیں اور چھوڑیں، چیک لسٹ کی پیش رفت ٹریک کریں، اور بناتے وقت #tag، @assignee یا p1 جیسی نحو استعمال کریں۔",
        "step3Title": "کی بورڈ اور AI",
        "step3Desc": "کمانڈ پیلیٹ کے لیے کسی بھی وقت Cmd/Ctrl + K دبائیں۔ AI ایجنٹوں کو کاموں پر براہ راست چلائیں۔",
    },
    "vi": {
        "stepLabel": "Bước {{current}} / {{total}}",
        "back": "Quay lại",
        "next": "Tiếp theo",
        "getStarted": "Bắt đầu",
        "close": "Đóng",
        "step1Title": "Chào mừng đến với Kandown",
        "step1Desc": "Bảng Kanban local-first của bạn, lưu bằng các tệp Markdown đơn giản trong ./tasks/. Không cơ sở dữ liệu, không khóa nhà cung cấp, phiên bản hóa bằng git.",
        "step2Title": "Quản lý tác vụ dễ dàng",
        "step2Desc": "Kéo và thả tác vụ giữa các cột, theo dõi tiến độ checklist và dùng cú pháp như #tag, @assignee hoặc p1 khi tạo.",
        "step3Title": "Bàn phím và AI",
        "step3Desc": "Nhấn Cmd/Ctrl + K bất kỳ lúc nào để mở bảng lệnh. Khởi chạy các tác nhân AI trực tiếp trên tác vụ.",
    },
    "zh": {
        "stepLabel": "第 {{current}} 步，共 {{total}} 步",
        "back": "上一步",
        "next": "下一步",
        "getStarted": "开始使用",
        "close": "关闭",
        "step1Title": "欢迎使用 Kandown",
        "step1Desc": "本地优先的看板，使用 ./tasks/ 中的纯 Markdown 文件。无需数据库，无需锁定，可通过 git 进行版本管理。",
        "step2Title": "简单的任务管理",
        "step2Desc": "在列之间拖放任务，跟踪清单进度，并在创建时使用 #tag、@assignee 或 p1 等内联语法。",
        "step3Title": "键盘与 AI",
        "step3Desc": "随时按 Cmd/Ctrl + K 打开命令面板。直接在任务上启动 AI 代理来自动化你的工作流。",
    },
}


def insert_at_sorted_position(d: dict, key: str, value) -> None:
    """📖 Rebuild the dict so `key` lands at its alphabetic slot. Lets us
    keep en.json-style ordering without rewriting every existing key."""
    new_items = [(k, v) for k, v in d.items() if k < key]
    new_items.append((key, value))
    new_items.extend((k, v) for k, v in d.items() if k > key)
    d.clear()
    d.update(new_items)


def main() -> None:
    if not LOCALES_DIR.is_dir():
        raise SystemExit(f"locales dir not found: {LOCALES_DIR}")

    expected = sorted(LOCALES_DIR.glob("*.json"))
    expected_names = sorted(p.stem for p in expected)
    expected_set = set(expected_names)
    translated = set(TRANSLATIONS.keys())

    missing = sorted(expected_set - translated - {"en"})
    extra = sorted(translated - expected_set)

    if missing:
        raise SystemExit(f"locales without translations: {missing}")
    if extra:
        raise SystemExit(f"translations without locale files: {extra}")

    for locale_name in expected_names:
        if locale_name == "en":
            # en.json already has the onboarding.* keys from the previous
            # edit, nothing to do.
            continue
        path = LOCALES_DIR / f"{locale_name}.json"
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
        existing = data.get("onboarding")
        desired = TRANSLATIONS[locale_name]
        if existing == desired:
            print(f"  {locale_name}: unchanged")
            continue
        insert_at_sorted_position(data, "onboarding", desired)
        with path.open("w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=2)
            fh.write("\n")
        print(f"  {locale_name}: wrote {len(desired)} keys")

    print(f"\nDone. {len(expected_names) - 1} locales updated (en skipped).")


if __name__ == "__main__":
    main()